### ISSUE TITLE
Support aliases

### ISSUE THREAD

**Issue by kathgironpe** [davidyorr/vim-es6-unused-imports#1]
Thank you so much for this plugin...

I find it useful. 

I'd like to raise this issue and maybe help when I have time.

<img width="523" alt="screen shot 2018-07-01 at 10 35 32 pm" src="https://user-images.githubusercontent.com/50656/42134442-5ef00a2e-7d7f-11e8-93e5-ff6bb14685ae.png">

Aliases should be supported IMHO.

**Comment by davidyorr** [comment]
i agree that aliases should be supported. if you figure out a fix i can merge a PR. i can also take a look when i get a chance
