### ISSUE TITLE
Support React Stateless Functional Components

### ISSUE THREAD

**Issue by djm158** [davidyorr/vim-es6-unused-imports#3]
example:

![image](https://user-images.githubusercontent.com/8800738/45779620-7b1d5100-bc29-11e8-8fa3-c0f56b6b2b02.png)

**Comment by davidyorr** [comment]
im not sure what the best solution is, but because of this exact case i did add the option to exclude words. so as a workaround you could do

```vim
let g:es6_imports_excludes = ['React', 'Component']
```

**Comment by djm158** [comment]
Yeah, not sure if there's a better solution other than that, figured I'd bring it up to see if it generates any discussion. 😊

**Comment by djm158** [comment]
Hey I actually realized my screenshot is a mistake. You don't need to import `{Component}` from functional stateless components.

![image](https://user-images.githubusercontent.com/8800738/45790033-d31b7e00-bc50-11e8-8a50-011c9cfea2ea.png)

Turns out it works just fine 😊
